apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zyz9i5adb-go 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=zyz9i5adb-go
    backstage.io/kubernetes-id: zyz9i5adb-go 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-test-organization-jk/zyz9i5adb-go
    jenkins.io/job-full-name: zyz9i5adb-go
    quay.io/repository-slug: rhtap-test-organization-jk/rhtap-qe
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 